# Generated by Django 5.1.4 on 2025-01-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0002_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, null=True, unique=True),
        ),
    ]
